### PR TITLE
Changing visualization structure

### PR DESCRIPTION
**Pull request by dcurrey88**
I moved some files around and changed the way data quality and the bash script work so it fits better into the cortex module setup.

### CODE REVIEW

**Comment by avaidyam** [comment]
@lukeoftheshire @dcurrey88 Do we have any other "magic"/"internal use only" scripts for visualizations or other use-cases we can clean up and integrate within the package? If so, we should do that!

**Comment by dcurrey88** [comment]
@avaidyam Yes. I am planning to add some general correlation map between passive / active feature code as well, but it's not ready to be added yet.

**Comment by lukeoftheshire** [comment]
> @lukeoftheshire @dcurrey88 Do we have any other "magic"/"internal use only" scripts for visualizations or other use-cases we can clean up and integrate within the package? If so, we should do that!

I do, but I'll fold that into another PR as I think it would take too long to integrate here

**Review by lukeoftheshire — APPROVED** [review]
LGTM!

**Pull request merged**
