### PR TITLE
Lucy new feature

### PR DESCRIPTION
**Pull request by lugray1**

### CODE REVIEW

**Comment by dcurrey88** [comment]
This looks good! Please add a unittest to confirm that nearby device count works when you have some data.

**Comment by lugray1** [comment]
> 

Done, thanks Danielle! Let me know if there is anything else I should add/change

**Comment by dcurrey88** [comment]
First, it looks like some of the call tests don't pass. @carlan1 may be able to help with figuring out what is going on there. Second, please delete raw/wifi.py, unless I'm mistaken that feature doesn't exist anymore. Finally, please make sure to filter out wifi events from the count.

**Comment by lugray1** [comment]
> Fixed that, am editing docs now.

**Review by dcurrey88 — APPROVED** [review]
I made a minor change and removed wifi.py from the pylint file. Looks great!

**Pull request merged**
