### PR TITLE
Logging added to working Secondary features

### PR DESCRIPTION
**Pull request by rydmel**
Logging added to working secondary features, and decorators added to most secondary features

### CODE REVIEW

**Comment by avaidyam** [comment]
@rbilden Could you switch Cortex to this branch and test `hometime` out after doing the `LAMP_SERVER_ADDRESS` change that @jlavoie9 shared yesterday? Share your cell output/logs here too!

**Review by ryan-hays — APPROVED** [review]

**Comment by ryan-hays** [comment]
@rbilden Hometime merged into master, so please test

**Comment by rbilden** [comment]
image
still seems to be running slowly--started running it ~10 min ago

**Comment by avaidyam** [comment]
@rbilden Your configuration still looks wrong based on what @jlavoie9 discovered yesterday! Please fix that and restart the kernel. You should **never** use `LAMP.connect()` if you're using Cortex.

**Comment by rbilden** [comment]
image
@avaidyam got it, still not working it stays on the above screen and then I get the following message
image

**Comment by jlavoie9** [comment]
> @rbilden Your configuration still looks wrong based on what @jlavoie9 discovered yesterday! Please fix that and restart the kernel. You should **never** use `LAMP.connect()` if you're using Cortex.

To confirm, `LAMP.connect` has no effect on cortex. Delete your `LAMP.connect` and add `os.environ['LAMP_SERVER_ADDRESS']='api2.lamp.digital'`. Your access key and secret key are also taken from environment variables.

**Comment by avaidyam** [comment]
@rbilden You may have to close/reopen your IDE since it looks like Jupyter is what broke from your screenshot.

**Comment by rbilden** [comment]
@avaidyam I did try that

**Comment by ryan-hays** [comment]
> image
> still seems to be running slowly--started running it ~10 min ago
> @ryan-hays

To confirm, do you have `master` checked out? In the screenshot it looks like you are working on `update_hometime`

**Comment by rbilden** [comment]
@ryan-hays yes, my bad that was the wrong screenshot. I have switched and am still getting the same issue.

**Comment by avaidyam** [comment]
As in, it's not showing any logs about what it's doing? Can you confirm what the logs SHOULD look like, @rydmel?

**Comment by jlavoie9** [comment]
@rbilden Did you `git fetch ` or click the cloud with a down arrow at the top to get the latest changes

**Comment by rbilden** [comment]
@avaidyam I had recloned the cortex repo when I couldn't get the extension to work earlier.

**Pull request merged**
